spring.application.name=empresa_ti

spring.datasource.url=jdbc:mysql://localhost:3306/empresa_ti
spring.datasource.username=root
spring.datasource.password=ag871407

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true